version: '3.9'

volumes:
  storage_data:

services:
  storage_app:
    container_name: storage_app
    image: postgis/postgis:15-3.3
    volumes:
      - storage_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../.env
